mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', RedirectView.as_view(url='polls/'))
]

mysite/polls/urls.py
from . import views
from django.urls import path, re_path

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('summary/', views.summary, name='summary'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

mysite/polls/models/polls.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text + " | " + self.pub_date.ctime()


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core import serializers

import json
from django.db import connection


# Custom Packages
import polls.helpers as customutils

# Models
from .models import Question, Choice


def index(request: HttpRequest):
    limit = customutils.getInt(request.GET.get('limit', ''), 10)
    offset = customutils.getInt(request.GET.get('offset', ''), 0)
    search = request.GET.get('search', '')
    
    latest_question_list = Question.objects
    if len(search) > 0 and search != 'null':
        latest_question_list = latest_question_list.filter(question_text__icontains = search)
    
    latest_question_list = latest_question_list.order_by('-pub_date')[offset: offset + limit]
    query = "SELECT count(*) AS total_count FROM polls_question"
    if len(search) > 0 and search != 'null':
        query += " WHERE question_text LIKE '%{0}%'".format(search)
    
    query += " LIMIT {0}".format(limit, offset)
    mycursor = connection.cursor()
    mycursor.execute(query)
    result = mycursor.fetchone()
    total_count = 0
    if result is not None:
        total_count = result[0]

    return render(request, 'polls/index.html', {
        'latest_question_list': latest_question_list,
        'total_count': total_count
    })


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choices = []
    votes = []
    for row in json.loads(serializers.serialize("json",question.choice_set.all())):
        choices.append(row["fields"]["choice_text"])
        votes.append(row["fields"]["votes"])

    choices = customutils.safeEscapeString(json.dumps(choices))
    votes = customutils.safeEscapeString(json.dumps(votes))
    return render(request, 'polls/results.html', {'question': question, 'choices': choices, 'votes': votes})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Please choose an answer.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def summary(request):
    cursor = connection.cursor()
    cursor.execute('SELECT temp.question_text as question_text, SUM(temp.votes) as total_votes FROM (SELECT q.question_text question_text, c.votes votes FROM polls_question q INNER JOIN polls_choice c ON q.id = c.question_id GROUP BY q.question_text, c.votes) temp GROUP BY temp.question_text;')
    
    result = cursor.fetchall()
    questions = []
    votes = []
    totalQuestions = 0
    totalVotes = 0
    mostVotedQuestion = ''

    if len(result) > 0:
        totalQuestions = len(result)
        questions = customutils.safeEscapeString(json.dumps([i[0] for i in result]))
        votes = [i[1].__int__() for i in  result]
        totalVotes = sum(votes)

        mostVotedQuestion = max(result, key=lambda x: x[1].__int__())
        mostVotedQuestion = '{0} ({1})'.format(mostVotedQuestion[0], mostVotedQuestion[1])
    
    return render(request, 'polls/summary.html', {'questions': questions, 'votes': votes, 'totalQuestions': totalQuestions, 'totalVotes': totalVotes, 'mostVotedQuestion': mostVotedQuestion})

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.6.3.min.js"
      integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
      integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://kit.fontawesome.com/1250b03ed3.js"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <script src="{% static 'polls/js/utils.js' %}"></script>
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}" />
    <title>Polls App</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'polls:index' %}">Polls Viewer</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'polls:index' %}?limit=10"
                ><i class="fa-solid fa-house">&nbsp;</i>Home</i
              ></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:summary' %}"
                ><i class="fa-solid fa-square-poll-vertical">&nbsp;</i>Summary</i
              ></a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input
              class="form-control me-2"
              type="search"
              id="search_box"
              placeholder="Search"
              aria-label="Search"
            />
            <button
              class="btn btn-outline-success"
              type="button"
              onclick="filterPolls()"
            >
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
        {% block mainbody %}
        {% endblock %}
  </body>
</html>

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html" %} {% block mainbody %}
<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  <div class="d-flex flex-row justify-content-center mt-4">
    <div class="card w-75">
      <div class="card-body">
        <h5 class="card-title text-center fw-bold">Poll {{question.id }}</h5>
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
          <strong>{{ error_message }}</strong>
        </div>
        {% endif %}
        <p class="card-text fw-bold">Question: {{ question.question_text }}</p>
        {% for choice in question.choice_set.all %}
        <div class="form-check mb-4">
          <input
            class="form-check-input"
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}"
          />
          <label class="form-check-label" for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}
          </label>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">
          <i class="fa-solid fa-check"></i> &nbsp;Submit
        </button>
      </div>
    </div>
  </div>
</form>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block mainbody %}
  {% if latest_question_list%} 
    {% for question in latest_question_list %}
      {% if forloop.counter0|divisibleby:"4" %}
        <div class="d-flex flex-row">
      {% endif %}
      <div class="p-2 m-2">
        <div class="card shadow-sm" style="width: 18rem">
          <div class="card-body pb-1">
            <p class="card-text fw-bold">{{question.question_text}}</p>
            <a
              href="{% url 'polls:detail' question.id %}"
              data-toggle="modal"
              data-target="#exampleModal"
              class="btn btn-success"
              ><i class="fa-solid fa-reply"></i> &nbsp; Answer</a
            >
            <a
              href="{% url 'polls:results' question.id %}"
              data-toggle="modal"
              data-target="#exampleModal"
              class="btn btn-warning"
              ><i class="fa-thin fa-square-poll-vertical"></i> &nbsp; Results</a
            >
            <hr />
            <p
              class="card-text mt-2 text-center"
              style="font-size: 0.7em; font-weight: bold"
            >
              Published: {{question.pub_date}}
            </p>
          </div>
        </div>
      </div>
      {% if forloop.counter0|add:"1"|divisibleby:"4" %}
        </div>
      {% elif forloop.counter == latest_question_list|length %}
        </div>
      {% endif %}
    {% endfor%}
  {% else %}
    <div class="container">
      <div class="row">
        <div class="col-3"></div>
        <div class="col-6 mt-5">
          <div class="alert alert-warning" role="alert">Polls not found!!!</div>
        </div>
      </div>
    </div>
  {% endif %}

  <div class="container">
    <div class="row">
      <div class="col-4"></div>
      <div class="col-8">      
      <nav aria-label="...">
        <ul id = 'pagination_block' class="pagination">
          <li class="page-item disabled">
        </ul>
      </nav>
      </div>
    </div>
  </div>
  <script>
      const attachNewNode = (parent, type, classes) => {
        const node = document.createElement(type);
        for(let i=0; i<classes.length; i++){
          node.classList.add(classes[i]);
        }
        parent.appendChild(node);
        return node;
      }

      const attachRedirectionNode = (parent, type, classes, text, paramsObj) => {
        const node = document.createElement(type);
        for(let i=0; i<classes.length; i++){
          node.classList.add(classes[i]);
        }
        
        const params = new URLSearchParams(paramsObj).toString();
        node.href = `{% url 'polls:index' %}?${params}`;
        node.tabIndex='-1';
        node.innerHTML=text;
        parent.appendChild(node);
        return node;
      }

      const getQueryParams = (paramsObj) => {
        const params = new Proxy(new URLSearchParams(window.location.search), {
          get: (searchParams, prop) => searchParams.get(prop),
        });

        const keys = Object.keys(paramsObj);
        for(let i=0; i<keys.length; i++) {
          paramsObj[keys[i]] = params[keys[i]];  
        }

        return paramsObj;
      }

      const buildQueryParams = (paramsObj, i) => {
        paramsObj['offset'] = i*10;
        paramsObj['limit'] = 10;
        return paramsObj; 
      }

      const preparePagination = ()=>{
        const total_count = JSON.parse('{{total_count}}');
        let paramsObj = getQueryParams({'offset': undefined, 'limit': undefined, 'search': undefined});
        const main = document.getElementById('pagination_block');
      
        if(paramsObj['offset'] === null) {
          paramsObj['offset'] = 0;
        }
        
        paramsObj['limit'] = 10;
        let newParamsObj = {...paramsObj, offset: 0};
        for(let i=0; i<Math.floor(total_count/10); i++){
          let classesList = ['page-item'];
          if(i*10 == paramsObj['offset']){
            classesList.push('active');
          }
          const child = attachNewNode(main, 'li', classesList);
          attachRedirectionNode(child, 'a', ['page-link'], ""+(i+1), newParamsObj);
          newParamsObj = buildQueryParams(newParamsObj, i + 1);
        }
        
      }

      window.onload = preparePagination
  </script>
{% endblock %}

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>

    <ul>
      {% for choice in question.choice_set.all %}
      <li>
        {{ choice.choice_text }} -- {{ choice.votes }} vote {{
        choice.votes|pluralize }}
      </li>
      {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
  </body>
</html>

mysite/polls/templates/polls/summary.html
{% extends "polls/base.html" %} {% block mainbody %}
<div class="container-fluid">
  <div class="row m-5">
    <div class="col-5">
      <div class="alert alert-success fw-bold" role="alert">
        Total Questions: {{ totalQuestions }}
      </div>
      <div class="alert alert-success fw-bold" role="alert">
        Total Votes: {{ totalVotes }}
      </div>
      <div class="alert alert-success fw-bold" role="alert">
        Most Voted Question: {{ mostVotedQuestion }}
      </div>
    </div>
    <div class="col-7">
      <div class="d-flex flex-row justify-content-center">
        <canvas id="myChart" style="width: 80%; max-width: 600px"></canvas>
      </div>
    </div>
  </div>
</div>

<script>
  const displayGraph = (xLabels, yLabels, title, graphType = "bar") => {
    let barColors = [];
    for (let i = 0; i < votesList.length; i++) {
      const randomColor = "#000000".replace(/0/g, function () {
        return (~~(Math.random() * 16)).toString(16);
      });
      barColors.push(randomColor);
    }

    new Chart("myChart", {
      type: graphType,
      data: {
        labels: xLabels,
        datasets: [
          {
            backgroundColor: barColors,
            data: yLabels,
          },
        ],
      },
      options: {
        legend: { display: false },
        title: {
          display: true,
          text: title,
        },
      },
    });
  };

  const questionsList = JSON.parse("{{questions|safe}}");
  const votesList = JSON.parse("{{votes|safe}}");
  const title = "Total Questions and No of Votes";
  displayGraph(questionsList, votesList, title, "pie");
</script>

{% endblock %}